# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0388b0d2729ee22dff42a1767020a3d850271c0fccedfb40b02e977cb7cced0c7e260beaca9401a4342b441713f984ffa596cbfeeeadf5f70c6dcd7211f6cb8c

test:
  secret_key_base: f77fa9c40ca94d3eab564f66505d208f5c179b8f9a4287074e4877eae6a20b6ce874e6048089440f2cd1d70fbe2998254b938697b83cbd791077a53b32868dc9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
